---
title: "Lab 4 T Tests Activity"
author: "Kayla Carew"
format: docx
date: Today
---
# Question 1
```{r}
rm(list = ls()) # empty out environment
library(tidyverse)
library(effectsize)
setwd("~/Documents/Fordham - PhD/First Year Courses 2025-2026/Fall Semester 2025/Intro to Psych Stats/Lab/R_Lab/Lab 4")

library(dataset)
data(CO2, package = "datasets")
glimpse(CO2)
help("CO2")
#DV - Uptake #Type - Factor 
# Examine Type of Plants (From Quebec or Mississpi) amount of Uptake to see if they differ 
```

#Testing Assumptions for Independent T-Test
```{r}
#Test for outliers
CO2 %>% group_by(Type) %>% 
  summarize(mean = mean(uptake), 
            tmean = mean(uptake, trim = .05))
#Very close for each group

ggplot(CO2, aes(Type, uptake)) + geom_boxplot()
#Quebec looks like it has some outliers

#Test for Normality
library(e1071)
CO2 %>% group_by(Type) %>% 
  summarize(mean = mean(uptake), sd = sd(uptake), 
            skew = skewness(uptake), kurt = kurtosis(uptake))
#Mean for Quebec is 33.5 Mean for Miss is 20.9
#SD for Quebec is 9.7 and for Miss is 7.8
#Histogram for Quebec
ggplot(CO2 %>% filter(Type == "Quebec"), aes(uptake)) + 
  geom_histogram(aes(y = after_stat(density)), bins = 8) + 
  stat_function(fun = dnorm, 
                args = list(mean = 33.5, sd = 9.7), col = "blue")
#Histogram for Mississpi
ggplot(CO2 %>% filter(Type == "Mississippi"), aes(uptake)) + 
  geom_histogram(aes(y = after_stat(density)), bins = 10) + 
  stat_function(fun = dnorm, 
                args = list(mean = 33.5, sd = 9.7), col = "blue")

#QQ Plots
ggplot(CO2, aes(sample = uptake)) + stat_qq() + 
  stat_qq_line() + facet_wrap(~Type)

#NOT NORMAL and has some outliers

library(car)
leveneTest(uptake ~ Type, data = CO2)
#Do not need to use Welch because levenes test is not violated
```
# Independent T-Test for

```{r}
 t.test(uptake ~ Type, CO2)
#there is a significant difference in the Uptake amount for Plants between Quebec and Mississppi
```


```{r}
#Effect size
6.6/sqrt(84)
#There is a medium-large effect of the Type
```
#Question 2
```{r}
data(sleep, package = "datasets")
glimpse(sleep)
help("sleep")

sleep2 <- sleep %>%
pivot_wider(id_cols = ID,
names_from = group,
names_prefix = "group",
values_from = extra)
```

#Check assumptions for paired t-test
```{r}
sleep2 <- sleep2 %>%
group_by(ID) %>%
  mutate(difference = group2 - group1)
#calculates the difference scores
#Test for Normality
ggplot(sleep2, aes(sample = difference )) + stat_qq() + 
  stat_qq_line()
#Test for outliers
ggplot(sleep2, aes(group1)) + geom_boxplot()
ggplot(sleep2, aes(group2)) + geom_boxplot() 

t.test(sleep2$group2, sleep2$group1, 
       paired = TRUE, alternative = "two.sided")
#T-Statistic 4.1 - There is a signficant difference in sleep pre and post drug given (group factor)
#Effect size
4.1/sqrt(10)
#This value is mean diff/ sd diff value --> Difference is 1.29 std deviation away from population mean difference
```