{
  "hash": "b72e682fa5e14f9ace03c48e46c9ff16",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 9: Multiple Linear Regression I\"\n---\n\n## Packages for Today (Install if Needed)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\nlibrary(tidyverse)\nlibrary(GGally) # used for pairs plots\nlibrary(gridExtra) # used to plot multiple graphs simultaneously\n```\n:::\n\n\n## Data for Today\n\nToday, we'll work with a dataset that includes a large number of assorted variables associated with the 50 U.S. States (including the educational expenditures and SAT information that we worked with in lecture). \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_xlsx(\"States.xlsx\", sheet = 1)\n```\n:::\n\n\nThe second sheet of the Excel file includes more details about each of the variables in the dataset. Take a few minutes to glance through this dataset. \n\n## Fitting a Linear Regression Model\n\nThe syntax for fitting a regression model is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(DV ~ IV1 + IV2 + IV3, dataset)\n```\n:::\n\n\n* Replace \"DV\" and \"IV\"s with column names from the dataset\n* Any number of IVs can be added by separating terms with the \"+\" sign\n* Save the output from `lm` as an object\n\n## Fitting the Regression Model\n\nExample:\n\nSuppose we hypothesize that the number of airports in a state is primarily a function of the size of the state and its population. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(Nairports ~ TotalSqMiles + Population, dat)\n```\n:::\n\n\nThere is no printed output from running this code, we have only saved the regression results as a new object in our environment.\n\n## Fitting the Regression Model\n\nTo extract the estimated model coefficients, use the `coef()` function around the `lm()` output. It can sometimes help to round these values to 3, 4, or 5 decimal points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(coef(mod1), 7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept) TotalSqMiles   Population \n   2.9877042    0.0000318    0.0000005 \n```\n\n\n:::\n:::\n\n\nThe predicted # of airports = 2.99 + 0.00003TotalSqMiles + .0000005Population\n\n* 2.99 is the predicted number of airports for a state with no land or water area (impossible) and no population (also somewhat impossible).\n* For every additional square mile in a state, we expect .00003 more airports, *holding population constant*.\n* For every additional person in a state, we expect .0000005 more airports, *holding area constant*.\n\n## Fitting the Regression Model\n\nA more detailed summary of the model is given by the `summary()` command. This gives the model coefficients, $t$-tests for each coefficient, $R^2$, adjusted $R^2$, and the omnibus $F$-test. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Nairports ~ TotalSqMiles + Population, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.2301 -1.5090 -0.2061  1.1620  5.3398 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.988e+00  4.624e-01   6.462 5.36e-08 ***\nTotalSqMiles 3.180e-05  3.215e-06   9.891 4.56e-13 ***\nPopulation   4.562e-07  4.208e-08  10.842 2.21e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.172 on 47 degrees of freedom\nMultiple R-squared:  0.8403,\tAdjusted R-squared:  0.8335 \nF-statistic: 123.7 on 2 and 47 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe omnibus $F$ test is significant, and each coefficient is significantly different than zero according to the $t$-tests. The multiple $R^2 = .8403$ (adjusted = .8335), indicating very high predictive accuracy. \n\n## Fitting the Standardized Regression Model\n\nThe result on the previous slides may seem a little strange in that both the coefficient for `TotalSqMiles` and the coefficient for `Population` are nearly zero. This has to do with the scale of the variables. \n\n* One way to put variables \"on the same scale\" is to fit the standardized regression model. To do this, we can standardize each variable using the `scale()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- lm(scale(Nairports) ~ scale(TotalSqMiles) + \n             scale(Population), dat)\n\nround(coef(mod2), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        (Intercept) scale(TotalSqMiles)   scale(Population) \n             0.0000              0.5814              0.6374 \n```\n\n\n:::\n:::\n\n\n* For every *standard deviation increase* in total square miles, we expect a .58 standard deviation increase in the number of airports, holding population constant.\n* For every *standard deviation increase* in population, we expect a .64 standard deviation in the number of airports, holding area constant.\n\n## Fitting the Standardized Regression Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = scale(Nairports) ~ scale(TotalSqMiles) + scale(Population), \n    data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.79474 -0.28350 -0.03871  0.21832  1.00323 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         3.612e-17  5.770e-02   0.000        1    \nscale(TotalSqMiles) 5.814e-01  5.878e-02   9.891 4.56e-13 ***\nscale(Population)   6.374e-01  5.878e-02  10.842 2.21e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.408 on 47 degrees of freedom\nMultiple R-squared:  0.8403,\tAdjusted R-squared:  0.8335 \nF-statistic: 123.7 on 2 and 47 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe model fit ($t$-tests, omnibus $F$-test, $R^2$, adjusted $R^2$) is identical to the unstandardized model, the only difference is that the coefficients are on a standardized scale.\n\n## Exploring Data\n\nLet's now do what we should have done in the first place - explore the data graphically! A \"pairs plot\", or scatterplot matrix, is particularly useful for this purpose. The `ggpairs()` function in the `GGally` package allows us to do this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggpairs(dat[, c(\"Nairports\", \"TotalSqMiles\", \"Population\")])\n```\n\n::: {.cell-output-display}\n![](Multiple_Linear_Regression_I_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n\nAll variables have high positive skew!\n\n## Exploring Data\n\nThere are some outliers, and potential nonlinearities in these data. Perhaps if we take the natural logs of `Nairports`, `TotalSquareMiles` and `Population`, these variable will be more linearly related. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% \n  mutate(logNairports = log(Nairports),\n         logTotalSqMiles = log(TotalSqMiles),\n         logPopulation = log(Population))\n```\n:::\n\n\n## Exploring Data\n\nThen, make the pairs plot again:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggpairs(dat[,c(\"logNairports\", \"logTotalSqMiles\", \"logPopulation\")])\n```\n\n::: {.cell-output-display}\n![](Multiple_Linear_Regression_I_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\nNot only does the skewness of our variables change, but the correlations among the variables also change when taking logs (this will happen with any nonlinear transformation).\n\n## Fitting the Regression Model\n\nLet's next fit the model with the transformed variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod3 <- lm(logNairports ~ logTotalSqMiles + logPopulation, dat)\nsummary(mod3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = logNairports ~ logTotalSqMiles + logPopulation, \n    data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.58033 -0.23730 -0.03901  0.17861  0.78330 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     -4.65013    0.77839  -5.974 2.95e-07 ***\nlogTotalSqMiles  0.31700    0.04390   7.220 3.79e-09 ***\nlogPopulation    0.21129    0.04756   4.442 5.38e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3333 on 47 degrees of freedom\nMultiple R-squared:  0.6549,\tAdjusted R-squared:  0.6402 \nF-statistic:  44.6 on 2 and 47 DF,  p-value: 1.385e-11\n```\n\n\n:::\n:::\n\n\nNotice that the multiple $R^2$ is now much lower. All 3 estimated regression coefficients have also changed substantially.\n\n* Even though $R^2$ is lower, this model may be preferable (e.g., more generalizable) than the previous model.\n\n* Part of the reason why has to do with the effects of outliers, which we'll focus on next week.\n\n* We should also consider model assumptions before trusting these results too much (also next week).\n\n## Categorical Variables\n\nFor another example, let's explore what happens when we use categorical variables as IVs. In the dataset, there are three dummy-coded variables (`RegionNortheast`, `RegionSouth`, and `RegionNorthCentral` corresponding to four regions of the U.S (Northeast, South, NorthCentral, and West).\n\nFirst, run the following to create a new factor-type variable named `Region`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% \n  mutate(Region = case_when(RegionNorthEast == 1 ~ \"Northeast\",\n                            RegionSouth == 1 ~ \"South\",\n                            RegionNorthCentral == 1  ~ \"NorthCentral\",\n                            # next line says that 3 0s indicates \"West\"\n                            .default = \"West\"))\n```\n:::\n\n\n## Regression Model\n\n\nThe `lm()` function automatically implements dummy coding when it detects a categorical variable! Just make sure you know what the reference category is.\n\n- You could equivalently use the dummy coded variables directly, but this may use a different reference category\n\n::: {.panel-tabset}\n\n## Automatic Dummies\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod4 <- lm(HighestElevation ~ Region, dat)\nsummary(mod4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = HighestElevation ~ Region, data = dat)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -3453  -1239   -389   1045   6426 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       2828.2      622.9   4.540 4.04e-05 ***\nRegionNortheast    838.0      951.5   0.881    0.383    \nRegionSouth        969.8      824.0   1.177    0.245    \nRegionWest       11055.9      863.8  12.799  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2158 on 46 degrees of freedom\nMultiple R-squared:  0.8311,\tAdjusted R-squared:  0.8201 \nF-statistic: 75.46 on 3 and 46 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Manual Dummies\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod4b <- lm(HighestElevation ~ RegionNorthEast + \n              RegionSouth + RegionNorthCentral, dat)\nsummary(mod4b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = HighestElevation ~ RegionNorthEast + RegionSouth + \n    RegionNorthCentral, data = dat)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n -3453  -1239   -389   1045   6426 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)         13884.1      598.5   23.20  < 2e-16 ***\nRegionNorthEast    -10218.0      935.7  -10.92  2.3e-14 ***\nRegionSouth        -10086.1      805.7  -12.52  < 2e-16 ***\nRegionNorthCentral -11055.9      863.8  -12.80  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2158 on 46 degrees of freedom\nMultiple R-squared:  0.8311,\tAdjusted R-squared:  0.8201 \nF-statistic: 75.46 on 3 and 46 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n:::\n\n\n## Categorical Variables\n\nBecause our only IV is discrete with 4 cateogries, we might instead think to run an ANOVA.\n\nA one-way ANOVA predicting the highest elevation by region is identical to a regression model on dummy variables. To see, why let's run both models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod5 <- aov(HighestElevation ~ Region, dat)\nsummary(mod5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df    Sum Sq   Mean Sq F value Pr(>F)    \nRegion       3 1.054e+09 351351539   75.46 <2e-16 ***\nResiduals   46 2.142e+08   4656250                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\nThe $F$ test for the main effect of region in the ANOVA is identical to the omnibus $F$ test in the regression model!\n\n## Categorical Variables\n\nThe main \"difference\" (not a real difference) between the two models is how the results are analyzed. ANOVA models mostly focus on proportion of variance explained, while regression models put more emphasis on regression coefficients. \n\nIn the fitted regression model, \n\nPredicted highest elevation = 2828.2 + 838 $\\times$ `NorthEast` + 969.8 $\\times$ `South` + 11055.9  $\\times$ `West`\n\n* 2828.2 is the mean for the `NorthCentral` (reference category)\n* 2828.2 + 830 = 3666.2 is the mean for the `NorthEast`\n* 2828.2 + 969.8 = 3798 is the mean for the `South`\n* 2828.2 + 11055.9 = 13884.1 is the mean for the `West`\n\n## Double Checking\n\nIt is good to double check that what we are doing makes sense, even if it is something pretty simple.\n\nHere are the means calculated from the data, which matches the model-predicted averages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat %>% \n  group_by(Region) %>% \n    summarise(mean = mean(HighestElevation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  Region         mean\n  <chr>         <dbl>\n1 NorthCentral  2828.\n2 Northeast     3666.\n3 South         3798.\n4 West         13884.\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "Multiple_Linear_Regression_I_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}