{
  "hash": "520a5de87aa29777b39c73b3decf6997",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 11: Moderation, Mediation, and Missing Data\"\n---\n\n## Packages for Today (Install if Needed)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggeffects)\nlibrary(interactions)\nlibrary(mediation)\nlibrary(lavaan)\n\n\n# optional packages - only used for one type of missing data handling\nlibrary(mice)\nlibrary(brms) \n```\n:::\n\n\n\n## Functions for Moderation and Mediation\n\n* `lm(DV ~ IV1 * IV2, dat)`: moderation (interactive) model\n* mediation::mediate(model.m, model.y, treat, mediator, boot = TRUE)\n  - `model.m`: fitted `lm()` object for path \"a\"\n  - `model.y`: fitted `lm()` object for paths \"b\" and \"c'\"\n  - `treat`: name of the treatment variable ($x$)\n  - `mediator`: name of the mediator variable ($m$)\n  - `boot = TRUE`: use simulation to find result\n  \n  \n  \n## Data for Today\n\nToday we'll work with another educational dataset, this one a survey of college students. The variables that we'll work with include:\n\n* final: final exam score\n* atndrte: percent of lectures attended\n* priGPA: GPA prior to that semester\n* termgpa: GPA for the current term\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\ndat <- read_dta(\"Lab_11_attend.dta\")\n```\n:::\n\n\n# Moderation\n\n## Moderation \n\nTo illustrate a moderation analysis, we will predict final exam scores from prior GPA, using attendance rate as a moderator. In other words, we want to know whether the linear regression of `final exam scores` on `prior GPA` *changes* as a function of `attendance rate`.\n\nFirst, we want to center the predictors, prior GPA and attendance rate. To center variables, subtract the mean from each score. It is usually convenient to add centered variables to the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% mutate(priGPA_C = priGPA - mean(priGPA),\n                      atndrte_C = atndrte - mean(atndrte))\n```\n:::\n\n\n## Moderation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodrmod <- lm(final ~ priGPA_C * atndrte_C, dat)\nsummary(modrmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = final ~ priGPA_C * atndrte_C, data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-16.4387  -2.8093  -0.2672   3.0143  11.3030 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        25.63475    0.18284 140.202  < 2e-16 ***\npriGPA_C            3.07500    0.34254   8.977  < 2e-16 ***\natndrte_C           0.01494    0.01236   1.209 0.227255    \npriGPA_C:atndrte_C  0.06474    0.01881   3.441 0.000614 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.354 on 676 degrees of freedom\nMultiple R-squared:  0.1491,\tAdjusted R-squared:  0.1454 \nF-statistic:  39.5 on 3 and 676 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Significant Interaction Term\n\nThe $t$-test for the moderation effect is statistically significant at $\\alpha = .05$: $t(676) = 3.44, p < .001$.\n\nExactly as we did for 2-Way ANOVA, we now need to evaluate the main effects at different values of the moderator!\n\nTo probe the moderation effect, we can plug in different values of the moderator.\n\nFor example:\n\n* mean of moderator\n* one standard deviation above the mean of the moderator\n* one standard deviation below the mean of the moderator\n\n\n## Using `ggeffects`\n\nWe can also use `ggeffects` to do a moderation plot for us. By default, it will give us three lines at 1 SD below the mean of the moderator, at the mean of the moderator, and 1 SD above the mean of the moderator\n\nPlot on next slide\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggp1 <- ggpredict(modrmod, \n                  terms = c(\"priGPA_C\", \"atndrte_C\"))\nplot(ggp1)\n```\n:::\n\n\n## Using `ggefffects`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Lab_11_Moderation_Mediation_Missing_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## Using `ggefffects`\n\nWe can also choose different custom values of the moderator by putting them in square brackets. This might make sense if there are special values of the moderator of interest. for example, let's say we wanted lines at -10, 0, and 10 for attendance centered.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggp2 <- ggpredict(mod_res, \n                  terms = c(\"priGPA_C\", \n                            \"atndrte_C[-10, 0, 10]\"))\nplot(ggp2)\n```\n:::\n\n\nPlot on next slide\n\n## Using `ggefffects`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Lab_11_Moderation_Mediation_Missing_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n\n## Using the `interactions` Package\n\nCreate a `sim_slopes` object with the `sim_slopes()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimple_slopes <- sim_slopes(modrmod,\n                            pred = priGPA_C,\n                            modx = atndrte_C,\n                            jnplot = TRUE,\n                            confint = TRUE)\n```\n:::\n\n\nThis results in a list object that contains both numerical information about simple slopes and a Johnson-Neyman plot\n\n## The Simple Slopes\n\nYou can print the values of the slopes of the focal predictor at different values of the moderator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(simple_slopes$slopes,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Value of atndrte_C  Est.  S.E.  2.5% 97.5% t val. p\n1            -17.047 1.971 0.500 0.989 2.954  3.939 0\n2              0.000 3.075 0.343 2.402 3.748  8.977 0\n3             17.047 4.179 0.436 3.323 5.034  9.590 0\n```\n\n\n:::\n:::\n\n\n\n## The Johnson-Neyman Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimple_slopes$jnplot\n```\n\n::: {.cell-output-display}\n![](Lab_11_Moderation_Mediation_Missing_files/figure-revealjs/unnamed-chunk-11-1.png){width=80%}\n:::\n:::\n\n\n# Mediation\n\n## Mediation: Single Mediator Model\n\nPath diagram for the single mediator model:\n\n```{.R}\n                     ----------\n                    |Mediator m|\n              a  /   ----------  \\ b\n                /                 \\\n       -----------        c'       ---------\n      |Predictor x| ------------> |Outcome y|\n       -----------                  ---------\n\n```\n\n\nFor illustration, we will again model final exam scores as the outcome ($y$), but now with ACT scores as the predictor ($x$), and termgpa as a potential mediator ($m$).\n\n## Mediation\n\nThe first thing we need to do is fit two regression models:\n\n1. Mediator m ~ predictor x\n\n2. Outcome y ~ predictor x + mediator m\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_m <- lm(termgpa ~ ACT, dat) # path a\nmod_y <- lm(final ~ ACT + termgpa, dat) # paths b and c'\nround(summary(mod_m)$coefficients, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)    1.434      0.179   8.015        0\nACT            0.052      0.008   6.598        0\n```\n\n\n:::\n\n```{.r .cell-code}\nround(summary(mod_y)$coefficients, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   10.802      1.019  10.599        0\nACT            0.339      0.044   7.676        0\ntermgpa        2.871      0.209  13.731        0\n```\n\n\n:::\n:::\n\n\n## Mediation: Bootstrapping\n\nFor the bootstrapping, we feed the `mod_m` and `mod_y` objects to the `mediate` function from the `mediation` package. Because this method requires random sampling (here, over 1,000 bootstrap samples), it takes a few seconds to run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mediate(model.m = mod_m, \n                model.y = mod_y,\n                treat = \"ACT\", \n                mediator = \"termgpa\", \n                boot = TRUE, sims = 1000))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCausal Mediation Analysis \n\nNonparametric Bootstrap Confidence Intervals with the Percentile Method\n\n               Estimate 95% CI Lower 95% CI Upper   p-value    \nACME           0.148797     0.099732     0.208675 < 2.2e-16 ***\nADE            0.338608     0.250386     0.422386 < 2.2e-16 ***\nTotal Effect   0.487406     0.387096     0.584332 < 2.2e-16 ***\nProp. Mediated 0.305284     0.214259     0.415819 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 680 \n\n\nSimulations: 1000 \n```\n\n\n:::\n:::\n\n\nThe estimated mediation effect $\\hat{a}\\times \\hat{b}$ is .149 (ACME), and is significantly different from zero, 95% CI = [.098, .209]. \n\n(Results shown on the next slide might vary by a slight amount due to the variability associated with random sampling.)\n\n\n## Mediation: Bootstrapping\n\n\\footnotesize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mediate(model.m = mod_m, model.y = mod_y,\n                treat = \"ACT\", mediator = \"termgpa\", boot = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCausal Mediation Analysis \n\nNonparametric Bootstrap Confidence Intervals with the Percentile Method\n\n               Estimate 95% CI Lower 95% CI Upper   p-value    \nACME            0.14880      0.10054      0.19959 < 2.2e-16 ***\nADE             0.33861      0.26081      0.42216 < 2.2e-16 ***\nTotal Effect    0.48741      0.40106      0.57749 < 2.2e-16 ***\nProp. Mediated  0.30528      0.21652      0.40224 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 680 \n\n\nSimulations: 1000 \n```\n\n\n:::\n:::\n\n\n## Mediation: Bootstrapping\n\nThe `lavaan` package provides another way to fit a mediation model that makes it easier to handle missing data\n\n* First, we use `lavaan`-specific syntax to fit the model\n\n* `final`, `termgpa`, and `ACT` are columns in the data set\n\n* `a`, `b`, and `c` are user-provided labels for regression coefficients\n\n* `~` indicates regression, `:=` indicates a calculated combination of parameters\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedmod <- \"\nfinal ~ b * termgpa + c * ACT\ntermgpa ~ a * ACT\n\nind := a*b    # calculate the indirect effect\ntot := a*b+c  # calculate the direct effect\n\"\n```\n:::\n\n\n## Mediation: Bootstrapping\n\nWe can fit this model using the `sem` function from `lavaan`\n\n* `se = \"boot\"` means to calculate bootstrapped standard errors\n\n* `bootstrap` indicates the number of bootstrap replications\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlav_res <- sem(medmod, data = dat, se = \"boot\", bootstrap = 1000)\nsummary(lav_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6-19 ended normally after 1 iteration\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         5\n\n  Number of observations                           680\n\nModel Test User Model:\n                                                      \n  Test statistic                                 0.000\n  Degrees of freedom                                 0\n\nParameter Estimates:\n\n  Standard errors                            Bootstrap\n  Number of requested bootstrap draws             1000\n  Number of successful bootstrap draws            1000\n\nRegressions:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  final ~                                             \n    termgpa    (b)    2.871    0.222   12.955    0.000\n    ACT        (c)    0.339    0.045    7.604    0.000\n  termgpa ~                                           \n    ACT        (a)    0.052    0.008    6.736    0.000\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .final            15.064    0.836   18.025    0.000\n   .termgpa           0.509    0.032   16.151    0.000\n\nDefined Parameters:\n                   Estimate  Std.Err  z-value  P(>|z|)\n    ind               0.149    0.026    5.734    0.000\n    tot               0.487    0.048   10.148    0.000\n```\n\n\n:::\n:::\n\n\n\n## Appendix: Missing Data Handling\n\nIn lecture, we learned about **multiple imputation** and **maximum likelihood** as methods to account for missing data. \n\n* In our dataset, there are 6 missing values of `hwrte`.\n\n* In the following slides, we will illustrate these methods for the following regression:\n\n\n```{}\ntermgpa ~ priGPA + hwrte\n```\n\n## Appendix: Maximum Likelihood with `lavaan`\n\nThe `lavaan` package requires specifying the model as a character string first:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_mod <- \"termgpa ~ priGPA + hwrte\"\n```\n:::\n\n\nThen, we fit the model with the `sem` function\n\n* `std.ov = TRUE` means to standardize variables - this can help estimation work correctly and avoid errors\n\n* `missing = \"FIML\"` uses Full Information Maximum Likelihood to estimate parameters from all available data\n\n* `fixed.x = FALSE` ensures proper missing data handling if there is missing data in the predictors\n\n* `estimator = \"MLR\"` uses maximum likelihood estimation with robust standard errors, which is preferable when data are not normally distributed\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngpa_lavaan <- sem(gpa_mod, data = dat, std.ov = TRUE,\n                  missing = \"FIML\", fixed.x = FALSE,\n                  estimator = \"MLR\")\n```\n:::\n\n\n## Appendix: Maximum Likelihood with `lavaan`\n\nThe output gives a lot more information that we're used to from `lm`\n\n* The \"Regressions:\" for `termgpa ~` are the regression coefficients such that\n\n$$\\widehat{termgpa} = .003 + .547 \\times priGPA + .340 \\times hwrte$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gpa_lavaan, header = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nParameter Estimates:\n\n  Standard errors                             Sandwich\n  Information bread                           Observed\n  Observed information based on                Hessian\n\nRegressions:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  termgpa ~                                           \n    priGPA            0.547    0.029   18.837    0.000\n    hwrte             0.340    0.034    9.926    0.000\n\nCovariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  priGPA ~~                                           \n    hwrte             0.312    0.043    7.202    0.000\n\nIntercepts:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .termgpa           0.003    0.026    0.117    0.907\n    priGPA            0.000    0.038    0.000    1.000\n    hwrte            -0.009    0.039   -0.231    0.817\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .termgpa           0.468    0.030   15.405    0.000\n    priGPA            0.999    0.051   19.653    0.000\n    hwrte             1.007    0.091   11.030    0.000\n```\n\n\n:::\n:::\n\n\n## Appendix: Multiple Imputation with `mice`\n\nThe `mice` function in the `mice` package is useful for multiple imputation\n\n* The `m = 5` argument means to create 5 imputed data sets\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimputed_data <- mice(data = dat, m = 5)\n```\n:::\n\n\nWe can look to see what the imputed values are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimputed_data$imp$hwrte\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1    2    3    4    5\n50  50.0 50.0 37.5 12.5 50.0\n185 37.5 75.0 50.0 87.5 87.5\n326 50.0 62.5 75.0 75.0 62.5\n474 12.5 37.5 50.0 12.5 12.5\n511 50.0 50.0 37.5 37.5 50.0\n513 12.5 37.5 12.5 37.5 12.5\n```\n\n\n:::\n:::\n\n\n\n## Appendix: Multiple Imputation with `mice` and `lm`\n\nThe `mice` also includes functions to fit the model to the imputed datasets and pool results\n\n* Note: don't use this for moderation models!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfits <- with(imputed_data, lm(termgpa ~ priGPA + hwrte))\nsummary(pool(fits))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         term    estimate  std.error statistic       df      p.value\n1 (Intercept) -0.45155293 0.11074244 -4.077506 671.0017 5.098293e-05\n2      priGPA  0.73189435 0.03716633 19.692403 674.2179 1.527842e-68\n3       hwrte  0.01324588 0.00102768 12.889114 671.0848 4.028197e-34\n```\n\n\n:::\n:::\n\n## Appendix: Multiple Imputation with `mice` and `brms`\n\nA Bayesian alternative to pooling with `lm` and `mice` is to use the `brm_multiple` function in the `brms` package\n\n* Note that this can take some time to run, depending on how fast your computer is\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfits_brms <- brm_multiple(termgpa ~ priGPA + hwrte, imputed_data)\n```\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fits_brms)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity \nFormula: termgpa ~ priGPA + hwrte \n   Data: imputed_data (Number of observations: 680) \n  Draws: 20 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 20000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI\nIntercept    -0.45      0.11    -0.67    -0.23\npriGPA        0.73      0.04     0.66     0.81\nhwrte         0.01      0.00     0.01     0.02\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI\nsigma     0.50      0.01     0.48     0.53\n\nDraws were sampled using sampling(NUTS). Overall Rhat and ESS estimates\nare not informative for brm_multiple models and are hence not displayed.\nPlease see ?brm_multiple for how to assess convergence of such models.\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}