{
  "hash": "907d849fbb7e2b6678afd238b6a1e267",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 5: Power Analysis\"\n---\n\n## Packages for Today (Install If Needed)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(pwr)\n```\n:::\n\n\n\n## Overview\n\nThe primary package we'll use for conducting power analyses is `pwr`.\n\nFunctions we will be using today: \n\n* `pwr.norm.test`\n* `pwr.t.test`\n* `pwr.t2n.test`\n* `pwr.chisq.test`\n\n\n## The Logic of the `pwr` Package Functions\n\nMost of the functions of the `pwr` structure work in the same way in that the usually have four main arguments:\n\n- The effect size, `d =`, in the case of *t*-tests.\n- The sample size, `n =`\n- The type I error rate, `sig.level =`\n- The desired power of your experiment, `power =` \n\nSet one of these four arguments to `NULL` to solve for that value (e.g., `n = NULL` means to solve for sample size).\n\n- Arguments may be named differently depending on the type of power analysis, so always check the function help page. \n\n \n## Power for $z$-tests\n\nIn the case of a *z*-test, to get **power** given effect size, sample size, and desired type I error rate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.norm.test(d = .5, \n              n = 10, \n              sig.level = .05, \n              power = NULL,\n              alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Mean power calculation for normal distribution with known variance \n\n              d = 0.5\n              n = 10\n      sig.level = 0.05\n          power = 0.3526081\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n\n## Power for $z$-tests\n\nTo get required **sample size** given effect size, desired type I error rate, and power:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.norm.test(d = .5, \n              n = NULL, \n              sig.level = .05, \n              power = .8,\n              alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Mean power calculation for normal distribution with known variance \n\n              d = 0.5\n              n = 31.39544\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n## Power for $z$-tests\n\nThe `pwr` package also includes a plotting method. This means that we can use the function `plot()` with the output from any power calculation results. (they don't look very attractive)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pwr.norm.test(d = .5, \n              n = 10, \n              sig.level = .05, \n              power = NULL,\n              alternative = \"two.sided\"))\n```\n\n::: {.cell-output-display}\n![](Power_Analysis_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\n## One-sample $t$-test\n\nIn lab 4 we ran a one sample *t*-test to test whether average restaurant ratings were significantly different from 3. with $d = .21$ and $N = 200$ we can do a retrospective power calculation: \n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = 200, \n           d = .21, \n           sig.level = .05, \n           power = NULL, \n           type = \"one.sample\", \n           alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 200\n              d = 0.21\n      sig.level = 0.05\n          power = 0.8402593\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\nOur power was around .84. What does this mean?\n\n## One-sample $t$-test\n\nWhat if I want to repeat the previous \"experiment\", and I want to know the sample size that I would need to have .8, .9, and .95 power?\n\n::: panel-tabset\n\n## power = .80\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = NULL, d = .21, sig.level = .05, power = .80,\n           type = \"one.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 179.9089\n              d = 0.21\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n## power = .90\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = NULL, d = .21, sig.level = .05, power = .90,\n           type = \"one.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 240.1924\n              d = 0.21\n      sig.level = 0.05\n          power = 0.9\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n## power = .95\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = NULL, d = .21, sig.level = .05, power = .95,\n           type = \"one.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     One-sample t test power calculation \n\n              n = 296.5928\n              d = 0.21\n      sig.level = 0.05\n          power = 0.95\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n:::\n\nFor a priori power analysis, we want to round up, so $N = 180, 241, 297$ for 80%, 90%, and 95% power.\n\n## Paired-samples $t$-test\n\nPower analysis for a paired-sample *t*-test is the same as the one-sample $t$-test. Remember that you will output the number of **pairs** that you need. \n\n## Independent-samples $t$-test\n\nFor the independent samples $t$-test, we can use `pwr.t.test` if we have equal sample sizes, or `pwr.t2n.test` for unequal sample sizes. \n\nIn the case of lab 4, where we were testing whether males ($n_{1} = 112$) and females ($n_{2} = 82$) were significantly different on average food rating. the estimate effect was $d = .17$, but the difference was not significant, $p = .224$. In retrospect, their power to detect an effect was only .21! \n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t2n.test(n1 = 112, n2 = 82, d = .17, sig.level = .05,\n             power = NULL, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     t test power calculation \n\n             n1 = 112\n             n2 = 82\n              d = 0.17\n      sig.level = 0.05\n          power = 0.2138687\n    alternative = two.sided\n```\n\n\n:::\n:::\n\n\n\n\n## Independent-samples $t$-test\n\nWhen planning data collection, plan for equally sized groups if possible because this maximizes power. Let's calculate a priori power assuming equal sample sizes and $d = .17$. \n\n::: panel-tabset\n\n## power = .80\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = NULL, d = .17, sig.level = .05, power = .80,\n           type = \"two.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 544.1358\n              d = 0.17\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n## power = .90\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = NULL, d = .17, sig.level = .05, power = .90,\n           type = \"two.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 728.1188\n              d = 0.17\n      sig.level = 0.05\n          power = 0.9\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n## power = .95\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.t.test(n = NULL, d = .17, sig.level = .05, power = .95,\n           type = \"two.sample\", alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Two-sample t test power calculation \n\n              n = 900.2493\n              d = 0.17\n      sig.level = 0.05\n          power = 0.95\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n\n\n:::\n:::\n\n\n:::\n\nIt turns out that $n$ = 545, 729, and 901 (quite large!) are the minimum sample sizes **in each group** for 80%, 90%, and 95% power.\n\n## Power for $\\chi^2$ tests\n\nWe can do the same for $\\chi^2$ tests using the `pwr.chi.test` function. The test does not distinguish between $\\chi^2$ goodness-of-fit and $\\chi^2$ test of independence. \n\nLet's use the airplane delays example from Lab 3. $\\chi^2(1) = 4.2$ with $N = 1100$. Our $W$ coefficient was $.06$. \n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.chisq.test(w = .06, N = 1100, df = 1, sig.level = .05, power = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Chi squared power calculation \n\n              w = 0.06\n              N = 1100\n             df = 1\n      sig.level = 0.05\n          power = 0.5120099\n\nNOTE: N is the number of observations\n```\n\n\n:::\n:::\n\n\nPower is about .51 to detect such a small effect. \n\n## Power for $\\chi^2$ tests\n\nFinally, let's conduct a priori power for this study.\n\n::: panel-tabset \n\n## power = 80\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.chisq.test(w = .06, N = NULL, df = 1, \n               sig.level = .05, power = .80)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Chi squared power calculation \n\n              w = 0.06\n              N = 2180.239\n             df = 1\n      sig.level = 0.05\n          power = 0.8\n\nNOTE: N is the number of observations\n```\n\n\n:::\n:::\n\n\n## power = .90\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.chisq.test(w = .06, N = NULL, df = 1, \n               sig.level = .05, power = .90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Chi squared power calculation \n\n              w = 0.06\n              N = 2918.728\n             df = 1\n      sig.level = 0.05\n          power = 0.9\n\nNOTE: N is the number of observations\n```\n\n\n:::\n:::\n\n\n## power = .95 \n\n\n::: {.cell}\n\n```{.r .cell-code}\npwr.chisq.test(w = .06, N = NULL, df = 1, \n               sig.level = .05, power = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     Chi squared power calculation \n\n              w = 0.06\n              N = 3609.641\n             df = 1\n      sig.level = 0.05\n          power = 0.95\n\nNOTE: N is the number of observations\n```\n\n\n:::\n:::\n\n\n:::\nFor this effect size, we would need data on $N = 2181, 2919, 3610$ flights for 80%, 90%, and 95% power.\n\n",
    "supporting": [
      "Power_Analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}