{
  "hash": "ab8f4968750cf0c66a58eceb6bd1ccc5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 13: Regression Extensions\"\n---\n\n\n## Packages for Today (Install if Needed)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(car)\nlibrary(lme4)\nlibrary(performance)\n```\n:::\n\n\n## Overview\n\nFunctions for logistic regression: \n\n* `glm(DV ~ IV1 + IV2 + ..., dat, family = binomial)`: fit the logistic regression model\n* `coef(glm())` or `summary(glm())$coefficients`: extract coefficients for a glm model\n* `fitted(glm())`: get fitted values (predicted probabilities)\n* `predict(glm(), newdata = ..., type = \"response\")`: get predicted probabilities for new data scored with the fitted model\n* `anova(glm1, test = \"LRT\")`: likelihood ratio test comparing `glm1` to the null model\n* `anova(glm1, glm2, test = \"LRT\")`: likelihood ratio test comparing `glm1` to `glm2` (where one model is a subset of the other model) \n\nFunction for multilevel regression:\n\n* `lmer(DV ~ CV + (1 | ID), dat)`\n  \n    - `dat`: dataset in long format\n\n    - `DV`: column name of dependent variable\n\n    - `ID`: column name of user IDs or other cluster variable\n\n    - `CV`: column name of covariate (may be IV)\n\n\n## Data For Today\n\nToday, we will try to predict volunteerism from personality characteristics. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"Cowles\", package = \"carData\")\n\nCowles %>% glimpse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,421\nColumns: 4\n$ neuroticism  <int> 16, 8, 5, 8, 9, 6, 8, 12, 15, 18, 12, 9, 13, 9, 12, 11, 5…\n$ extraversion <int> 13, 14, 16, 20, 19, 15, 10, 11, 16, 7, 16, 15, 11, 13, 16…\n$ sex          <fct> female, male, male, female, male, male, female, male, mal…\n$ volunteer    <fct> no, no, no, no, no, no, no, no, no, no, no, no, no, no, n…\n```\n\n\n:::\n:::\n\n\n## Exploring Data\n\nSuppose we hypothesize that higher extraversion is associated with higher rates of volunteering.\n\nWe might first calculate summary statistics for each group (volunteer vs. not):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCowles %>% group_by(volunteer, sex) %>% \n  summarize(n(), \n            mean(neuroticism), \n            mean(extraversion), .groups = \"keep\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n# Groups:   volunteer, sex [4]\n  volunteer sex    `n()` `mean(neuroticism)` `mean(extraversion)`\n  <fct>     <fct>  <int>               <dbl>                <dbl>\n1 no        female   431                12.2                 12.0\n2 no        male     393                10.5                 11.9\n3 yes       female   349                12.3                 12.9\n4 yes       male     248                10.4                 12.9\n```\n\n\n:::\n:::\n\n\nFrom these, it seems as if people who volunteer have higher extraversion. \n\n## Logistic Regression\n\nLet's next fit a logistic regression model with Extraversion as a predictor. \n\nThe command to fit logistic regression is `glm()`. The formula notation is the same as for linear regression, but we need to add the argument `family = binomial` to tell R that we want logistic regression instead of another GLM.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm1 <- glm(volunteer ~ extraversion, Cowles, \n            family = binomial)\n```\n:::\n\n\n## Logistic Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(summary(glm1)$coefficients, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate Std. Error z value Pr(>|z|)\n(Intercept)    -1.139      0.185  -6.146        0\nextraversion    0.066      0.014   4.640        0\n```\n\n\n:::\n:::\n\n\nThese results imply the following fitted equation:\n\n$\\hat{P}(volunteer) = \\frac{1}{1+\\exp(-(-1.14 + .07Extraversion))}$\n\n* -1.14 is the logit when Extraversion = 0 (highly introverted): $P = \\frac{1}{1 + \\exp(1.14)} = .24$\n\n* .07 is the increase in logit (predicted log odds of volunteering) for a one-point increase in Extraversion score\n\n## Coefficient interpretations\n\n* .07 is the increase in logit (predicted log odds of volunteering) for a one-point increase in Extraversion score\n\nOr\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(.07)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.072508\n```\n\n\n:::\n:::\n\n\n* For a one unit increase in Extraversion, volunteering becomes $exp(0.07) = 1.07$ times as likely. \n\nSometimes $exp(0.07) = 1.07$ might also be written as $e^{0.07} = 1.07$\n\n## Classification Accuracy\n\nTo evaluate accuracy, we need to get the fitted values for the training data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted1 <- fitted(glm1)\n```\n:::\n\n\nThen, we classify subjects as being predicted to volunteer or not based on a .5 cutoff.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass1 <- ifelse(fitted1 > .5, \"pred_yes\", \"pred_no\")\ntable(class1, Cowles$volunteer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          \nclass1      no yes\n  pred_no  765 526\n  pred_yes  59  71\n```\n\n\n:::\n\n```{.r .cell-code}\n(765 + 71)/(765 + 526 + 59 + 71)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5883181\n```\n\n\n:::\n:::\n\nWe get around 59% accuracy which is not great. Extraversion may not be very informative in relation to the outcome. \n\n## Model Comparison\n\n\nTo test whether extraversion has \"predictive power\" associated with it, we conduct a likelihood ratio test comparing `glm1` to the null model (a model with only an intercept).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(glm1, test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: volunteer\n\nTerms added sequentially (first to last)\n\n             Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    \nNULL                          1420     1933.5              \nextraversion  1   22.022      1419     1911.5 2.695e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nHere, we reject the null hypothesis that the null model fits as well as the model with extraversion. Therefore, we retain the model with extraversion as a predictor: $\\chi^2(dif, 1) = 22.022, p < .001$.\n\n\n## More than One Predictor\n\nPerhaps we can construct a better model by including neuroticism as a predictor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm2 <- glm(volunteer ~ extraversion + neuroticism, \n            Cowles, family = binomial)\nround(summary(glm2)$coefficients, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate Std. Error z value Pr(>|z|)\n(Intercept)    -1.281      0.237  -5.409    0.000\nextraversion    0.067      0.014   4.712    0.000\nneuroticism     0.011      0.011   0.967    0.333\n```\n\n\n:::\n:::\n\n\n## Model Comparison\n\nTo conduct the likelihood ratio test, we can use the `anova()` function with the two models that we want to compare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(glm1, glm2, test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n\nModel 1: volunteer ~ extraversion\nModel 2: volunteer ~ extraversion + neuroticism\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1      1419     1911.5                     \n2      1418     1910.5  1  0.93641   0.3332\n```\n\n\n:::\n:::\n\n\n$\\chi^2(dif, 1) = 0.936, p = .33$\n\nHere, we *retain* the null hypothesis, meaning that the simpler model (the model without neuroticism) fits just as well as the more complex model.\n\n\n## Wide vs. Long Data\n\nLong data has as many rows, as few columns as possible\n\n* Multiple rows for one subject\n* One column for the DV\n* One column for each IV\n\nWide data has fewer rows, more columns\n\n* e.g., One row per subject\n* Multiple columns for the DV at different IV levels\n\nLong data is usually preferred for data analysis\n\n* Some exceptions, such as for certain types of plots\n\n## Dataset 1: Stroop Effect\n\nWe'll begin by working through the Stroop Effect data from lecture. Remember that this dataset gives the proportion of correct responses for three different levels of contingency between words and colors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readxl)\ndat <- read_xlsx(\"Lab_13_Schmidt data.xlsx\",\n                 sheet = 2, range = \"B20:E257\", \n                 col_names = c(\"Subject\", \"High\", \"Medium\", \"Low\"))\ndat %>% glimpse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 238\nColumns: 4\n$ Subject <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…\n$ High    <dbl> 0.07692308, 0.20800000, 0.20472441, 0.26612903, 0.41739130, 0.…\n$ Medium  <dbl> 0.1200000, 0.3046875, 0.2890625, 0.3064516, 0.4300000, 0.38961…\n$ Low     <dbl> 0.1666667, 0.2968750, 0.2380952, 0.3622047, 0.4601770, 0.36144…\n```\n\n\n:::\n:::\n\n\n## Wide vs. Long Data\n\nIn this class, we have already seen some examples of moving between wide and long data.\n\ntidyverse functions:\n\n* `pivot_longer`: move from wide format to long format\n* `pivot_wider`: move from long format to wide format\n\nThe Stroop data are stored in wide format. To change to long format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_long <- dat %>% pivot_longer(cols = -Subject,\n                                 names_to = \"Contingency\", \n                                 values_to = \"PropError\")\n```\n:::\n\n\nThe `cols = -Subject` argument means to exclude the `Subject` column in the information that is shifted to the new columns. Instead, the Subject variable will be stretched in the long format. See next slide for the structure of `dat_long`.\n\n## Wide vs. Long Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_long %>% glimpse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 714\nColumns: 3\n$ Subject     <dbl> 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7…\n$ Contingency <chr> \"High\", \"Medium\", \"Low\", \"High\", \"Medium\", \"Low\", \"High\", …\n$ PropError   <dbl> 0.07692308, 0.12000000, 0.16666667, 0.20800000, 0.30468750…\n```\n\n\n:::\n:::\n\n\n* `Contingency` is the name of a new column taking values corresponding to the column names in the wide data set\n* `PropError` is the name of a new column taking (usually numeric) values of the actual cell entries\n* `Subject` is a variable storing information other than that stored in `Contingency` and `PropError`\n\n## Wide vs. Long Data\n\nTo return to wide format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_long %>% pivot_wider(id_cols = Subject, \n                         names_from = Contingency,\n                         values_from = PropError) %>% \n  glimpse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 238\nColumns: 4\n$ Subject <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…\n$ High    <dbl> 0.07692308, 0.20800000, 0.20472441, 0.26612903, 0.41739130, 0.…\n$ Medium  <dbl> 0.1200000, 0.3046875, 0.2890625, 0.3064516, 0.4300000, 0.38961…\n$ Low     <dbl> 0.1666667, 0.2968750, 0.2380952, 0.3622047, 0.4601770, 0.36144…\n```\n\n\n:::\n:::\n\n* `Contingency` name of (factor) variable in long data that contains wide format column names\n\n* `PropError` name of variable in long data that contains cell values\n\n## Data Cleaning\n\nAs a final piece of data cleaning, let's change the `Contingency` and `Subject` columns in `dat_long` to factors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_long <- dat_long %>% \n  mutate(Contingency = factor(Contingency),\n         Subject = factor(Subject))\n\ndat_long %>% glimpse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 714\nColumns: 3\n$ Subject     <fct> 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7…\n$ Contingency <fct> High, Medium, Low, High, Medium, Low, High, Medium, Low, H…\n$ PropError   <dbl> 0.07692308, 0.12000000, 0.16666667, 0.20800000, 0.30468750…\n```\n\n\n:::\n:::\n\n\n\n## Fitting multilevel models with `lmer`\n\nTo fit linear random-effects models, we can use the `lmer` function in the `lme4` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod <- lmer(PropError ~ (1 | Subject), dat_long)\n```\n:::\n\n\nThis syntax means that `PropError` is the DV, `Subject` is the random effect (the mean for each subject is a random variable), and `dat_long` is the dataset. \n\nFor now, this model doesn't account for the effect of `Contingency` level . It only models individual differences in the proportion of errors made.\n\n\n## Fitting multilevel models with `lmer`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: PropError ~ (1 | Subject)\n   Data: dat_long\n\nREML criterion at convergence: -1680.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.74685 -0.55952  0.04564  0.55973  2.84248 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 0.013775 0.11737 \n Residual             0.001966 0.04433 \nNumber of obs: 714, groups:  Subject, 238\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept) 0.344523   0.007787   44.25\n```\n\n\n:::\n:::\n\n\n* $\\hat{\\psi} = .013775$: estimated variance of the subject means (intercepts)\n\n* $\\hat{\\theta} = .001966$: estimated residual (within-subject) variance\n\n* $\\hat{\\beta}_0 = .344523$: estimated overall proportion of errors\n\n## Intraclass Correlation Coefficient\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(mod, ranef.comp = \"Variance\") # another way to view output\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: PropError ~ (1 | Subject)\n   Data: dat_long\nREML criterion at convergence: -1680.59\nRandom effects:\n Groups   Name        Variance\n Subject  (Intercept) 0.013775\n Residual             0.001966\nNumber of obs: 714, groups:  Subject, 238\nFixed Effects:\n(Intercept)  \n     0.3445  \n```\n\n\n:::\n:::\n\n\nThe ICC is the ratio of subject-level variance to total (subject + residual) variance: $\\frac{\\hat{\\psi}}{\\hat{\\psi} + \\hat{\\theta}}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n0.013775 / (0.013775 + 0.001966)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8751032\n```\n\n\n:::\n:::\n\n\n87.5% is the proportion of variance associated with individual differences in error rates\n\n## Intraclass Correlation Coefficient\n\nThe `performance` package also has an `icc()` function that can be called on `lmer` models. It will give you two values. We will generally want the **adjusted** ICC, though when there are no predictors they will be the same\n\n\n::: {.cell}\n\n```{.r .cell-code}\nicc(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.875\n  Unadjusted ICC: 0.875\n```\n\n\n:::\n:::\n\n\n## REML vs. ML\n\n`lmer` uses REML estimation by default. Set `REML = FALSE` for ML estimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lmer(PropError ~ (1 | Subject), dat_long, REML = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by maximum likelihood  ['lmerMod']\nFormula: PropError ~ (1 | Subject)\n   Data: dat_long\n\n      AIC       BIC    logLik -2*log(L)  df.resid \n  -1682.5   -1668.8     844.2   -1688.5       711 \n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.74719 -0.55942  0.04555  0.55939  2.84218 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Subject  (Intercept) 0.013714 0.11711 \n Residual             0.001966 0.04433 \nNumber of obs: 714, groups:  Subject, 238\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)  0.34452    0.00777   44.34\n```\n\n\n:::\n:::\n\n\nSome differences in random-effects estimates, but REML is preferred, especially when the number of clusters (persons) is small.\n\n## HLM With a Level-1 Covariate\n\nNext, let's add a fixed effect of `Contingency`. Similar to other regression coefficients, this assumes a linear relationship between `Contingency` and `PropError`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- lmer(PropError ~ Contingency + (1 | Subject), dat_long)\nprint(mod2, ranef.comp = \"Variance\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: PropError ~ Contingency + (1 | Subject)\n   Data: dat_long\nREML criterion at convergence: -1706.621\nRandom effects:\n Groups   Name        Variance\n Subject  (Intercept) 0.013831\n Residual             0.001796\nNumber of obs: 714, groups:  Subject, 238\nFixed Effects:\n      (Intercept)     ContingencyLow  ContingencyMedium  \n          0.33118            0.02659            0.01345  \n```\n\n\n:::\n:::\n\n\n::: columns\n:::: column\n\n* $\\hat{\\psi} = 0.013831$: estimated variance of the subject means (intercepts)\n\n* $\\hat{\\theta} = 0.001796$: estimated residual (within-subject) variance\n\n::::\n:::: column\n\n* $\\hat{\\beta}_0 = 0.33118$: estimated error proportion at high contingency\n\n* $\\hat{\\beta}_1 = 0.02659$: estimated increase in error rate for low vs. high contingency\n\n* $\\hat{\\beta}_2 = 0.01345$: estimated increase in error rate for medium vs. high contingency\n\n::::\n:::\n\n## Residual Intraclass Correlation\n\n* $\\hat{\\psi} = 0.013831$: estimated variance of the subject means (intercepts)\n\n* $\\hat{\\theta} = 0.001796$: estimated residual (within-subject) variance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nicc(mod2) # we want adjusted ICC here\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.885\n  Unadjusted ICC: 0.878\n```\n\n\n:::\n:::\n\n\nAfter accounting for the different trial types, 88.5% of the remaining variance is associated with individual mean differences.\n\n## Likelihood Ratio Test to Compare Models\n\nThe `anova` function will compare two competing models (fit to the same data) via a number of measures, including the likelihood ratio test. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod, mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: dat_long\nModels:\nmod: PropError ~ (1 | Subject)\nmod2: PropError ~ Contingency + (1 | Subject)\n     npar     AIC     BIC logLik -2*log(L)  Chisq Df Pr(>Chisq)    \nmod     3 -1682.5 -1668.8 844.23   -1688.5                         \nmod2    5 -1723.3 -1700.5 866.66   -1733.3 44.849  2  1.824e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThese results show significantly better fit for the model that includes `Contingency` as a covariate. There are 2 degrees of freedom for this test, associated with the 2 added dummy variables associated with the 3-category covariate in `mod2`.\n\n$\\Delta \\chi^2 (2) = 44.85, p < .001$\n",
    "supporting": [
      "Regression_Extensions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}