{
  "hash": "182aec102de02e9e1853a596fe20434c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 8: Factorial ANOVA\"\n---\n\n## Packages for Today\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(effectsize)\nlibrary(labelled)\nlibrary(car)\nlibrary(ez)\nlibrary(sjstats)\nlibrary(emmeans)\nlibrary(ggeffects)\n```\n:::\n\n\n## Data for Today\n\nRotten Tomatoes Data\n\n* IVs: Genre (Comedy vs. Drama vs. Sci-Fi) and Rating (PG vs. PG-13 vs. R)\n\n* DV: Box office revenue in millions of US dollars\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv(\"rotten_tomatoes_clean.csv\")\n\ndat %>% summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         id             title      audienceScore    tomatoMeter   \n Length   :1910   Length   :1910   Min.   :12.00   Min.   : 0.00  \n N.unique :1910   N.unique :1906   1st Qu.:47.00   1st Qu.:29.00  \n N.blank  :   0   N.blank  :   0   Median :63.00   Median :52.00  \n Min.nchar:   2   Min.nchar:   2   Mean   :61.92   Mean   :51.74  \n Max.nchar:  70   Max.nchar:  83   3rd Qu.:78.00   3rd Qu.:75.00  \n                                   Max.   :99.00   Max.   :98.00  \n                                                                  \n       rating       ratingContents releaseDateTheaters  releaseDateStreaming\n Length   :1910   Length   :1910   Min.   :1980-05-21   Min.   :1992-06-02  \n N.unique :   5   N.unique :1508   1st Qu.:2002-09-20   1st Qu.:2004-08-11  \n N.blank  :   0   N.blank  :   0   Median :2006-09-29   Median :2007-11-27  \n Min.nchar:   1   Min.nchar:  10   Mean   :2008-01-30   Mean   :2009-07-06  \n Max.nchar:   5   Max.nchar: 141   3rd Qu.:2013-11-01   3rd Qu.:2014-08-26  \n                                   Max.   :2023-02-03   Max.   :2023-03-28  \n                                                                            \n runtimeMinutes       genre       originalLanguage      director   \n Min.   : 74    Length   :1910   Length   :1910    Length   :1910  \n 1st Qu.: 95    N.unique :   3   N.unique :   1    N.unique :1121  \n Median :106    N.blank  :   0   N.blank  :   0    N.blank  :   0  \n Mean   :109    Min.nchar:   5   Min.nchar:   7    Min.nchar:   3  \n 3rd Qu.:119    Max.nchar:   6   Max.nchar:   7    Max.nchar: 176  \n Max.   :223                                                       \n                                                                   \n       writer         boxOffice       distributor        soundMix   \n Length   :1910   Length   :1910   Length   :1910   Length   :1910  \n N.unique :1675   N.unique :1160   N.unique : 241   N.unique : 266  \n N.blank  :   0   N.blank  :   0   N.blank  :   0   N.blank  :   0  \n Min.nchar:   7   Min.nchar:   4   Min.nchar:   3   Min.nchar:   4  \n Max.nchar: 145   Max.nchar:   7   Max.nchar: 156   Max.nchar:  85  \n                                                                    \n                                                                    \n  boxOfficeMil     \n Min.   :  0.0014  \n 1st Qu.:  5.7000  \n Median : 26.0500  \n Mean   : 53.2256  \n 3rd Qu.: 65.2250  \n Max.   :858.4000  \n NAs    :2         \n```\n\n\n:::\n:::\n\n\n## Data Cleaning\n\nThe DV of box office revenue (`boxOfficeMil`) is missing for two movies, so we will remove these from the data set:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% filter(!is.na(boxOfficeMil))\n```\n:::\n\n\nWe also want to omit movies without the PG, PG-13, or R ratings:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% filter(rating %in% c(\"PG\", \"PG-13\", \"R\"))\n```\n:::\n\n\nCheck for a balanced design (equal sample sizes for each combination of groups):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat %>% select(rating, genre) %>% table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       genre\nrating  Comedy Drama Sci-fi\n  PG       228    79     19\n  PG-13    334   284    133\n  R        273   508     46\n```\n\n\n:::\n:::\n\n## Box Plots\n\nLet's first explore the distribution of these data using box plots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat %>%\n  ggplot(aes(rating, boxOfficeMil, color = genre)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Factorial_ANOVA_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n## Data Transformation\n\nWe see (as we might have anticipated), a large number of positive outliers. This is an instance in which we might prefer to analyze a transformed outcome variable. This time, we'll use the Box-Cox transformation from Lecture 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::powerTransform(dat$boxOfficeMil)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated transformation parameter \ndat$boxOfficeMil \n       0.2164347 \n```\n\n\n:::\n\n```{.r .cell-code}\ndat <- dat %>% mutate(boxOffice_transformed = bcPower(boxOfficeMil, lambda = 0.2164347))\n```\n:::\n\n\n* With this transformation, we lose the ability to easily interpret the metric of the DV in favor of better meeting our test assumptions.\n\n* Be sure to always apply the exact same transformation to all values (no group-level transformations!)\n\n\n## Box Plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat %>%\n  ggplot(aes(rating, boxOffice_transformed, color = genre)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Factorial_ANOVA_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\nNow, we still have a few outliers, but our data should better meet the normality assumption with the transformed data.\n\n\n## Interaction Plot\n\nThe easiest way to make an interaction plot with `ggplot` is to create a new data set that includes group means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_means <- dat %>% \n  group_by(rating, genre) %>%\n  summarize(mean_boxOffice_transformed = mean(boxOffice_transformed), .groups = \"keep\")\n```\n:::\n\n\n## Interaction Plot\n\nThen, we can use this to draw an interaction plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat_means, \n       aes(rating, mean_boxOffice_transformed,\n           group = genre, \n           col = genre)) + \n  geom_point() + geom_line()\n```\n\n::: {.cell-output-display}\n![](Factorial_ANOVA_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\n## Formulas in R\n\nEarlier, we saw the `DV ~ IV` notation for formulas.\n\nWe can also use `DV ~ IV1 * IV2` to include both main effects and an interaction. \n\n* A longer way to write the same formula is `DV ~ IV1 + IV2 + IV1:IV2`.\n\n* The formula `DV ~ IV1:IV2` includes only the interaction, not the main effects.\n\n* The \"*\" notation implies all lower-order terms, and the \":\" notation implies only the interaction effect. \n\n## Two-Way ANOVA with `aov`\n\n**Warning**: Don't try this at home if you have unbalanced data!\n\n* If data are unbalanced, the main effects results depend on the order of the variables. Compare the two solutions:\n\n\n::: {.panel-tabset}\n\n## Rating * Genre\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_res <- aov(boxOffice_transformed ~ rating * genre, dat)\nsummary(aov_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value  Pr(>F)    \nrating          2   2997  1498.7  153.65 < 2e-16 ***\ngenre           2   1700   849.8   87.12 < 2e-16 ***\nrating:genre    4    140    35.0    3.59 0.00636 ** \nResiduals    1895  18484     9.8                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Genre * Rating\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_res <- aov(boxOffice_transformed ~ genre * rating, dat)\nsummary(aov_res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value  Pr(>F)    \ngenre           2   2938  1469.0  150.60 < 2e-16 ***\nrating          2   1759   879.5   90.17 < 2e-16 ***\ngenre:rating    4    140    35.0    3.59 0.00636 ** \nResiduals    1895  18484     9.8                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n:::\n\n\n## Two-Way ANOVA with `ezANOVA`\n\n`ezANOVA` in the `ez` package allows us to choose the sums of squares type. Here, we'll use type 3 SS since we are interested in a potential interaction effect. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nezANOVA(data = dat, dv = boxOffice_transformed,\n        between = c(genre, rating), wid = id,\n        type = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$ANOVA\n        Effect DFn  DFd         F            p p<.05         ges\n2        genre   2 1895 53.005050 3.990588e-23     * 0.052978294\n3       rating   2 1895 49.027459 1.738707e-21     * 0.049198302\n4 genre:rating   4 1895  3.590136 6.357627e-03     * 0.007521127\n\n$`Levene's Test for Homogeneity of Variance`\n  DFn  DFd      SSn      SSd        F            p p<.05\n1   8 1895 145.7517 6494.937 5.315667 1.284892e-06     *\n```\n\n\n:::\n:::\n\n\n\n## Two-Way ANOVA with `ezANOVA`\n\nWe rejected the null hypothesis for Levene's test, so we should use a correction for violations of homogeneity of variance. One option is to use White's adjustment, which is available with `ezANOVA`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nezANOVA(data = dat, dv = boxOffice_transformed,\n        between = c(genre, rating), wid = id,\n        type = 3, white.adjust = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$ANOVA\n        Effect DFn  DFd         F            p p<.05\n2        genre   2 1895 49.078462 1.656404e-21     *\n3       rating   2 1895 49.370951 1.254334e-21     *\n4 genre:rating   4 1895  3.370623 9.307024e-03     *\n\n$`Levene's Test for Homogeneity of Variance`\n  DFn  DFd      SSn      SSd        F            p p<.05\n1   8 1895 145.7517 6494.937 5.315667 1.284892e-06     *\n```\n\n\n:::\n:::\n\n\n## Two-Way ANOVA with `aov`\n\nAnother option if homogeneity is violated is to use weighted least squares. We can calculate and specify weights with the `aov` function.\n\nCalculate weights for each combination of groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- dat %>% \n  group_by(genre, rating) %>%\n  mutate(weight = 1 / var(boxOffice_transformed))\n```\n:::\n\n\nRun WLS ANOVA:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_aov <- aov(boxOffice_transformed ~ genre * rating, \n               dat, weights = weight)\n```\n:::\n\n\nBecause we have unbalanced data, we want to print type 2 or 3 sums of squares. Below, we find type 2 sums of squares using the `Anova` function from the `car` package. Note that we do **not** want to use this function to find type 3 sums of squares (use `ezAnova` instead).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAnova(res_aov, type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type II tests)\n\nResponse: boxOffice_transformed\n              Sum Sq   Df F value    Pr(>F)    \ngenre         171.39    2 85.6965 < 2.2e-16 ***\nrating        176.94    2 88.4680 < 2.2e-16 ***\ngenre:rating   13.76    4  3.4407  0.008243 ** \nResiduals    1895.00 1895                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## $r$-Family Effect Sizes \n\nNow that we have more effects in our ANOVA model, calculating effect size becomes more nuanced. **Partial** effect sizes enter the picture.\n\n- normally, $\\eta^2$ and $\\omega^2$ compare the variance explained of one of the ANOVA effects against the total variance.\n- *partial* $\\eta^2$ and $\\omega^2$ compare the variance explained of one of the ANOVA effects against the total variance *after* removing the variance already explained by other terms. \n\nIn practice, the numerator of the formula remains the same, but the denominator is always smaller for partial measures of effect sizes. This means that partial measures are *always* larger than their counterparts. \n\n## Effect Sizes \n\nThe `sjstats` package includes the `anova_stats` function for calculating $r$-family effect sizes. This is especially useful when you have multiple main effects and interaction effects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_stats(res_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\netasq | partial.etasq | omegasq | partial.omegasq | epsilonsq | cohens.f\n------------------------------------------------------------------------\n0.124 |         0.135 |   0.123 |           0.134 |     0.123 |    0.395\n0.074 |         0.085 |   0.073 |           0.084 |     0.073 |    0.306\n0.006 |         0.007 |   0.004 |           0.005 |     0.004 |    0.085\n      |               |         |                 |           |         \n\netasq |         term |    sumsq |   df |  meansq | statistic | p.value | power\n------------------------------------------------------------------------------\n0.124 |        genre |  295.737 |    2 | 147.869 |   147.869 |  < .001 | 1.000\n0.074 |       rating |  176.936 |    2 |  88.468 |    88.468 |  < .001 | 1.000\n0.006 | genre:rating |   13.763 |    4 |   3.441 |     3.441 |   0.008 | 0.860\n      |    Residuals | 1895.000 | 1895 |   1.000 |           |         |      \n```\n\n\n:::\n:::\n\n\nFor the interaction effect, $\\eta^2 = .006$, partial $\\eta^2 = .007$, $\\omega^2 = .004$, and partial $\\omega^2 = .005$.\n\n## Simple Main Effects by Rating Category\n\nWe found that the interaction effect is statistically significant at $\\alpha = .05$. To better understand what this result means, let's calculate simple main effects. You should *always* do this whenever an interaction in your model is significant. (If the interaction is **not** significant, look at the ordinary main effects in the ANOVA table instead.)\n\nLet's split the data by the three ratings, then look at the effects of genre on box office revenue within each rating category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_pg <- dat %>% filter(rating == \"PG\")\ndat_pg13 <- dat %>% filter(rating == \"PG-13\")\ndat_r <- dat %>% filter(rating == \"R\")\n```\n:::\n\n\nNext, we want the $MSW$ and $dfW$ from the original model. From before, $MSW = 9.8$ and $dfW = 1895$. (Note that the type of SS doesn't affect these numbers.)\n\n## Simple Main Effects by Rating Category\n\nNext, conduct a one-way ANOVA for each sub-data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(boxOffice_transformed ~ genre, dat_pg))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \ngenre         2  295.3  147.64   16.07 2.22e-07 ***\nResiduals   323 2967.1    9.19                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(boxOffice_transformed ~ genre, dat_pg13))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)    \ngenre         2   1104   552.1   62.92 <2e-16 ***\nResiduals   748   6563     8.8                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(boxOffice_transformed ~ genre, dat_r))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \ngenre         2    440  220.13   20.26 2.58e-09 ***\nResiduals   824   8955   10.87                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n* For the PG rated movies, $MSB = 147.64$ and $dfB = 2$.\n\n* For the PG-13 rated movies, $MSB = 552.1$ and $dfB = 2$.\n\n* For the R rated movies, $MSB = 220.13$ and $dfB = 2$.\n\n## Simple Main Effects by Rating Category\n\nThe $F$ test statistic equals $MSB/MSW$, where $MSB$ is from the sub-data sets, and $MSW$ is from the original ANOVA.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nF_pg <- 147.64 / 9.8\nF_pg13 <- 552.1 / 9.8\nF_r <- 220.13 / 9.8\n```\n:::\n\n\nTo find $p$-values, find the proportion of the $F$ distribution above each $F$ test statistic. Be sure to use $dfB$ from the sub-dataset and $dfW$ from the original dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npf(F_pg, df1 = 2, df2 = 1895, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.226199e-07\n```\n\n\n:::\n\n```{.r .cell-code}\npf(F_pg13, df1 = 2, df2 = 1895, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.710162e-24\n```\n\n\n:::\n\n```{.r .cell-code}\npf(F_r, df1 = 2, df2 = 1895, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.283538e-10\n```\n\n\n:::\n:::\n\n\nAt $\\alpha = .05$, there are significant differences in genre at all three rating categories.\n\n\n## Simple Main Effects Using `joint_tests()`\n\nAn easier way to do these tests imply is to use the `joint_tests()` function from the `emmeans` package. First we define an object using the `emmeans()` function with both grouping variables under `specs`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simple main effects calculation with the aov class results\nem1 <- emmeans(aov_res, specs = c(\"genre\",\"rating\"))\n\n# simple main effects calculation from the ezANOVA output\nez_res <- ezANOVA(data = dat, dv = boxOffice_transformed,\n            between = c(genre, rating), wid = id,\n            type = 3, white.adjust = TRUE, return_aov = TRUE)\nemmeans(ez_res$aov, specs = \"rating\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n rating emmean    SE   df lower.CL upper.CL\n PG       5.79 0.275 1895     5.25     6.33\n PG-13    5.75 0.123 1895     5.51     5.99\n R        3.72 0.172 1895     3.38     4.05\n\nResults are averaged over the levels of: genre \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nThen we can use `joint_tests()` to test whether the effect of `rating` is significant `by` the different levels of `rating``\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoint_tests(em1, by = \"rating\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrating = PG:\n model term df1  df2 F.ratio p.value\n genre        2 1895  15.135 <0.0001\n\nrating = PG-13:\n model term df1  df2 F.ratio p.value\n genre        2 1895  56.598 <0.0001\n\nrating = R:\n model term df1  df2 F.ratio p.value\n genre        2 1895  22.568 <0.0001\n```\n\n\n:::\n:::\n\n\nThe problem with this approach is we get much less detail in the output, some of which we need to compute effect sizes.\n\n## Post-Hoc Tests for Simple Main Effects\n\nIf there are 3 or more levels of the IV for simple effects, we can do post-hoc or a priori analyses like we learned about for the one-way ANOVA. For example, we can do Tukey's HSD for each rating separately.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(em1, by = \"rating\", adjust = \"tukey\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrating = PG:\n contrast          estimate    SE   df t.ratio p.value\n Comedy - Drama      2.2173 0.408 1895   5.438 <0.0001\n Comedy - (Sci-fi)  -0.0472 0.746 1895  -0.063  0.9978\n Drama - (Sci-fi)   -2.2645 0.798 1895  -2.838  0.0128\n\nrating = PG-13:\n contrast          estimate    SE   df t.ratio p.value\n Comedy - Drama      1.1140 0.252 1895   4.419 <0.0001\n Comedy - (Sci-fi)  -2.3774 0.320 1895  -7.424 <0.0001\n Drama - (Sci-fi)   -3.4914 0.328 1895 -10.639 <0.0001\n\nrating = R:\n contrast          estimate    SE   df t.ratio p.value\n Comedy - Drama      1.2152 0.234 1895   5.185 <0.0001\n Comedy - (Sci-fi)  -1.2339 0.498 1895  -2.479  0.0354\n Drama - (Sci-fi)   -2.4492 0.481 1895  -5.093 <0.0001\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\nAll pairwise comparisons are statistically significant except for comedy and sci-fi movies with a PG rating.\n\n## Effect Sizes for Simple Main Effects\n\nWe can use the equations from lecture and `R` as a calculator to find effect sizes for the simple main effect of genre separately for each rating category. \n\n$$Partial\\ \\eta^2_{simple} = \\frac{SSB_{simple}}{SSB_{simple} + SSW}$$\n$$\\eta^2_{simple} = \\frac{SSB_{simple}}{SST}$$\n\n$$Partial\\ \\omega^2_{simple} = \\frac{dfB(MSB_{simple} - MSW)}{SSB_{simple} + (N - dfB)MSW}$$\n$$\\omega^2_{simple} = \\frac{dfB(MSB_{simple} - MSW)}{SST + MSW}$$\n\n## Calculations: PG Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(boxOffice_transformed ~ genre, dat_pg))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \ngenre         2  295.3  147.64   16.07 2.22e-07 ***\nResiduals   323 2967.1    9.19                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n$N = 326$, $SS_{simple} = 295.3$, $MS_{simple} = 147.64$ and $df_{simple} = 2$ from the sub-data set. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(aov(boxOffice_transformed ~ genre * rating, dat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value  Pr(>F)    \ngenre           2   2938  1469.0  150.60 < 2e-16 ***\nrating          2   1759   879.5   90.17 < 2e-16 ***\ngenre:rating    4    140    35.0    3.59 0.00636 ** \nResiduals    1895  18484     9.8                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n$SS_{W} = 18484$, $df_{W} = 1895$, $MS_{W} = 9.8$, and $SS_{T} = 2938 + 1759 + 140 + 18484 = 23321$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n295.3 / 23321 # eta-squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01266241\n```\n\n\n:::\n\n```{.r .cell-code}\n295.3 / (295.3 + 18484) # partial eta-squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01572476\n```\n\n\n:::\n\n```{.r .cell-code}\n2 * (147.64 - 9.8) / (23321 + 9.8) # omega-squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01181614\n```\n\n\n:::\n\n```{.r .cell-code}\n2 * (147.64 - 9.8) / (295.3 + (326 - 2) * 9.8)  # partial omega-squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07943524\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Factorial_ANOVA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}